apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-maps-{{ .Release.Revision }}
data:
  MYSQL_DATABASE_URL: {{ .Release.Name }}-mysql
  MYSQL_DATABASE_PORT: "3306"
  APP_PROFILE: "prod"
  MYSQL_DATABASE_NAME: "UserServiceDB"



