apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-{{ .Release.Revision }}
data:
  MYSQL_PASSWORD: {{ .Values.mysql.auth.rootPassword | b64enc }}
  MYSQL_USER: {{ .Values.mysql.username | b64enc }}
  JWT_PREFIX: {{ .Values.jwt.prefix | b64enc }}
  JWT_SECRET: {{ .Values.jwt.secret | b64enc }}
  JWT_ISSUER: {{ .Values.jwt.issuer | b64enc }}



